name: CI

on: [ pull_request, push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Lint
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: node@${{ matrix.node_version }} on ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node_version: [ 10, 12, 14 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Install node@${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: Cache node modules
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-:  
    
    - name: npm install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Test
      run: npm test -- --ci --verbose

    # Run codecov after all builds, and only on a single environment
    - name: Gather Coverage
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '14'
      run: npm test -- --ci --coverage
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '14'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage-final.json


